name = "oem-backend"
main = "src/index.ts"
compatibility_date = "2026-07-22"
compatibility_flags = ["nodejs_compat"]

workers_dev = false
preview_urls = false

[cache]
enabled = true
cross_version_cache = true

[exports.default]
type = "worker"

[exports.default.cache]
enabled = false

[exports.PublicReadCache]
type = "worker"

[exports.PublicReadCache.cache]
enabled = true

[[routes]]
pattern = "api.opendfieldmap.org/*"
zone_name = "opendfieldmap.org"

[observability]
enabled = true

[observability.traces]
enabled = true
head_sampling_rate = 0.05

[[d1_databases]]
binding = "DB"
database_name = "oem-db"
database_id = "9ba2f958-0e96-48e8-9049-57ce712b5faf"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "UGC_BUCKET"
bucket_name = "opendfieldmap-ugc"

[[kv_namespaces]]
binding = "OEM_KV"
id = "d7432ab9beab4f858d10d661652ea7a2"

[[durable_objects.bindings]]
name = "OEM_USER_DO"
class_name = "OEMUserDO"

[[durable_objects.bindings]]
name = "OEM_STATS_DO"
class_name = "OEMStatsDO"

[[durable_objects.bindings]]
name = "OEM_IMG_TRANS"
class_name = "oem_imgTrans"

[[migrations]]
tag = "v1_progress_bitmap_sync"
new_sqlite_classes = ["OEMUserDO", "OEMStatsDO"]

[[migrations]]
tag = "v2_image_transcoder_container"
new_sqlite_classes = ["oem_imgTrans"]

[[containers]]
name = "oem-backend-oem_imgtrans"
class_name = "oem_imgTrans"
image = "./containers/oem_imgTrans/Dockerfile"
image_build_context = "./containers/oem_imgTrans"
max_instances = 5

[[queues.producers]]
binding = "OEM_MODQ"
queue = "oem-modq"

[[queues.consumers]]
queue = "oem-modq"
max_batch_size = 10
max_batch_timeout = 5
dead_letter_queue = "oem-modq-dlq"

[triggers]
crons = ["*/1 * * * *"]

[env.local]

[[env.local.d1_databases]]
binding = "DB"
database_name = "oem-db"
database_id = "9ba2f958-0e96-48e8-9049-57ce712b5faf"
migrations_dir = "migrations"

[[env.local.r2_buckets]]
binding = "UGC_BUCKET"
bucket_name = "opendfieldmap-ugc"

[[env.local.kv_namespaces]]
binding = "OEM_KV"
id = "d7432ab9beab4f858d10d661652ea7a2"

[[env.local.durable_objects.bindings]]
name = "OEM_USER_DO"
class_name = "OEMUserDO"

[[env.local.durable_objects.bindings]]
name = "OEM_STATS_DO"
class_name = "OEMStatsDO"

[[env.local.durable_objects.bindings]]
name = "OEM_IMG_TRANS"
class_name = "oem_imgTrans"

[[env.local.containers]]
name = "oem-backend-oem_imgtrans"
class_name = "oem_imgTrans"
image = "./containers/oem_imgTrans/Dockerfile"
image_build_context = "./containers/oem_imgTrans"
max_instances = 3

[[env.local.queues.producers]]
binding = "OEM_MODQ"
queue = "oem-modq"

[[env.local.queues.consumers]]
queue = "oem-modq"
max_batch_size = 10
max_batch_timeout = 5
dead_letter_queue = "oem-modq-dlq"
